/* ==============================
   data.js — Conjuntos de datos
   ============================== */

const DATA = {
  favorites: {
    id: "favorites",
    title: "⭐ Favoritos",
    note: "Añade aquí tus entradas favoritas haciendo clic en la ⭐ de cada fila.",
    headers: ["Elemento", "Descripción", "Sección"],
    rows: []
  },

  quiz: {
    id: "quiz",
    title: "🧠 Quiz Interactivo",
    note: "Pon a prueba tu vocabulario: escribe la traducción y recibe feedback inmediato.",
    headers: [],
    rows: []
  },

  /* ==============================
     Vocabulario 1000+ (estructura y ejemplo)
     ============================== */
  vocab: {
    id: "vocab",
    title: "Vocabulario (1000+)",
    note: "Palabras de alta frecuencia por categorías. Amplía fácilmente con Importar CSV/JSON.",
    headers: ["Inglés", "Español"],
    rows: [
      { type: "heading", text: "Function Words & Pronouns" },
      ["the", "el/la/los/las"], ["be", "ser/estar"], ["to", "a / para"], ["of", "de"],
      ["and", "y"], ["a", "un/una"], ["in", "en"], ["that", "que / ese/esa"], ["have", "tener"],
      ["I", "yo"], ["it", "ello/eso"], ["for", "para/por"], ["not", "no"], ["on", "en/sobre"],
      ["with", "con"], ["he", "él"], ["as", "como"], ["you", "tú/usted/ustedes"], ["do", "hacer"],
      ["at", "en/a"], ["this", "este/esta"], ["but", "pero"], ["his", "su (de él)"], ["by", "por"],
      ["from", "de/desde"], ["they", "ellos/ellas"], ["we", "nosotros/as"], ["say", "decir"],
      ["her", "su (de ella)"], ["she", "ella"], ["or", "o"], ["will", "aux. futuro"],
      ["my", "mi"], ["one", "uno/una"], ["all", "todo/as"], ["would", "aux. condicional"],
      ["there", "ahí/allí"], ["their", "su (de ellos)"], ["what", "qué"], ["so", "tan / así que"],
      ["up", "arriba"], ["out", "fuera"], ["if", "si"], ["about", "sobre/acerca de"],
      ["who", "quién"], ["get", "obtener"], ["which", "cuál"], ["go", "ir"], ["me", "me"],
      ["when", "cuando"], ["make", "hacer"], ["can", "poder"], ["like", "gustar / como"],
      ["time", "tiempo"], ["no", "no/ninguno"], ["just", "solo/justo"], ["him", "le/lo"],
      ["know", "saber/conocer"], ["take", "tomar"], ["people", "gente/personas"], ["into", "dentro de"],

      { type: "heading", text: "Common Nouns" },
      ["day", "día"], ["man", "hombre"], ["woman", "mujer"], ["child", "niño/a"],
      ["world", "mundo"], ["school", "escuela"], ["state", "estado"], ["family", "familia"],
      ["student", "estudiante"], ["group", "grupo"], ["country", "país"], ["problem", "problema"],
      ["hand", "mano"], ["part", "parte"], ["place", "lugar"], ["case", "caso"], ["week", "semana"],
      ["company", "empresa"], ["system", "sistema"], ["program", "programa"], ["question", "pregunta"],
      ["work", "trabajo"], ["night", "noche"], ["point", "punto"], ["home", "casa"],
      ["water", "agua"], ["room", "habitación"], ["mother", "madre"], ["area", "zona"], ["money", "dinero"],

      { type: "heading", text: "Adjectives" },
      ["good", "bueno"], ["new", "nuevo"], ["first", "primero"], ["last", "último"],
      ["long", "largo"], ["great", "genial/grande"], ["little", "pequeño/poco"],
      ["own", "propio"], ["other", "otro"], ["old", "viejo/antiguo"], ["right", "correcto/derecha"],
      ["big", "grande"], ["high", "alto"], ["different", "diferente"], ["small", "pequeño"], ["large", "grande"],
      ["next", "siguiente"], ["early", "temprano"], ["young", "joven"], ["important", "importante"],
      ["few", "pocos"], ["public", "público"], ["bad", "malo"], ["same", "mismo"], ["able", "capaz"],

      { type: "heading", text: "Common Verbs" },
      ["become", "convertirse"], ["leave", "dejar/marcharse"], ["need", "necesitar"], ["feel", "sentir"],
      ["seem", "parecer"], ["try", "intentar"], ["call", "llamar"], ["ask", "preguntar"],
      ["keep", "mantener"], ["let", "dejar"], ["begin", "empezar"], ["help", "ayudar"],
      ["show", "mostrar"], ["hear", "oír"], ["play", "jugar/tocar"], ["run", "correr"],
      ["move", "mover"], ["live", "vivir"], ["believe", "creer"], ["bring", "traer"],
      ["happen", "suceder"], ["write", "escribir"], ["provide", "proporcionar"], ["sit", "sentarse"],
      ["stand", "estar de pie"], ["lose", "perder"], ["pay", "pagar"], ["meet", "conocer/reunirse"],
      ["include", "incluir"], ["continue", "continuar"], ["set", "poner/establecer"], ["learn", "aprender"]
    ]
  },

  /* ==============================
     Verbos irregulares (200+) — muestra inicial
     ============================== */
  verbs_irregular: {
    id: "verbs_irregular",
    title: "Verbos Irregulares (200+)",
    note: "Base / Pasado / Participio + traducción. Haz clic en 🔊 para escuchar cada forma del verbo.",
    headers: ["Base", "Past", "Participle", "Español"],
    rows: [
      ["be", "was/were", "been", "ser/estar"],
      ["become", "became", "become", "convertirse"],
      ["begin", "began", "begun", "empezar"],
      ["break", "broke", "broken", "romper"],
      ["bring", "brought", "brought", "traer"],
      ["build", "built", "built", "construir"],
      ["buy", "bought", "bought", "comprar"],
      ["catch", "caught", "caught", "atrapar"],
      ["choose", "chose", "chosen", "elegir"],
      ["come", "came", "come", "venir"],
      ["cost", "cost", "cost", "costar"],
      ["cut", "cut", "cut", "cortar"],
      ["do", "did", "done", "hacer"],
      ["draw", "drew", "drawn", "dibujar"],
      ["drink", "drank", "drunk", "beber"],
      ["drive", "drove", "driven", "conducir"],
      ["eat", "ate", "eaten", "comer"],
      ["fall", "fell", "fallen", "caer"],
      ["feel", "felt", "felt", "sentir"],
      ["find", "found", "found", "encontrar"],
      ["fly", "flew", "flown", "volar"],
      ["forget", "forgot", "forgotten", "olvidar"],
      ["get", "got", "got/gotten", "obtener"],
      ["give", "gave", "given", "dar"],
      ["go", "went", "gone", "ir"],
      ["grow", "grew", "grown", "crecer"],
      ["have", "had", "had", "tener"],
      ["hear", "heard", "heard", "oír"],
      ["hold", "held", "held", "sostener"],
      ["keep", "kept", "kept", "mantener"],
      ["know", "knew", "known", "saber/conocer"],
      ["leave", "left", "left", "dejar/marcharse"],
      ["lead", "led", "led", "liderar"],
      ["let", "let", "let", "dejar"],
      ["lose", "lost", "lost", "perder"],
      ["make", "made", "made", "hacer/fabricar"],
      ["meet", "met", "met", "conocer/reunirse"],
      ["pay", "paid", "paid", "pagar"],
      ["put", "put", "put", "poner"],
      ["read", "read", "read", "leer"],
      ["ride", "rode", "ridden", "montar"],
      ["ring", "rang", "rung", "sonar"],
      ["run", "ran", "run", "correr"],
      ["say", "said", "said", "decir"],
      ["see", "saw", "seen", "ver"],
      ["sell", "sold", "sold", "vender"],
      ["send", "sent", "sent", "enviar"],
      ["set", "set", "set", "poner/establecer"],
      ["sit", "sat", "sat", "sentarse"],
      ["speak", "spoke", "spoken", "hablar"],
      ["spend", "spent", "spent", "gastar/pasar (tiempo)"],
      ["stand", "stood", "stood", "estar de pie"],
      ["take", "took", "taken", "tomar"],
      ["teach", "taught", "taught", "enseñar"],
      ["tell", "told", "told", "contar/decir"],
      ["think", "thought", "thought", "pensar"],
      ["understand", "understood", "understood", "entender"],
      ["wear", "wore", "worn", "llevar (ropa)"],
      ["win", "won", "won", "ganar"],
      ["write", "wrote", "written", "escribir"]
    ]
  },

  /* ==============================
     Verbos regulares (200+) — muestra inicial
     ============================== */
  verbs_regular: {
    id: "verbs_regular",
    title: "Verbos Regulares (200+)",
    note: "Base / Pasado (-ed) / Significado. El pasado y participio de los verbos regulares es el mismo.",
    headers: ["Base", "Past / Participle", "Español"],
    rows: [
      ["accept", "accepted", "aceptar"],
      ["add", "added", "añadir"],
      ["allow", "allowed", "permitir"],
      ["answer", "answered", "responder"],
      ["arrive", "arrived", "llegar"],
      ["ask", "asked", "preguntar"],
      ["believe", "believed", "creer"],
      ["call", "called", "llamar"],
      ["change", "changed", "cambiar"],
      ["clean", "cleaned", "limpiar"],
      ["close", "closed", "cerrar"],
      ["cook", "cooked", "cocinar"],
      ["dance", "danced", "bailar"],
      ["decide", "decided", "decidir"],
      ["enjoy", "enjoyed", "disfrutar"],
      ["explain", "explained", "explicar"],
      ["help", "helped", "ayudar"],
      ["improve", "improved", "mejorar"],
      ["include", "included", "incluir"],
      ["learn", "learned", "aprender"],
      ["like", "liked", "gustar"],
      ["live", "lived", "vivir"],
      ["listen", "listened", "escuchar"],
      ["love", "loved", "amar"],
      ["need", "needed", "necesitar"],
      ["open", "opened", "abrir"],
      ["play", "played", "jugar/tocar"],
      ["rain", "rained", "llover"],
      ["remember", "remembered", "recordar"],
      ["start", "started", "empezar"],
      ["talk", "talked", "hablar"],
      ["travel", "traveled", "viajar"],
      ["use", "used", "usar"],
      ["wait", "waited", "esperar"],
      ["want", "wanted", "querer"],
      ["watch", "watched", "ver"],
      ["work", "worked", "trabajar"]
    ]
  },

  /* ==============================
     Phrasal Verbs (100+)
     ============================== */
  phrasal: {
    id: "phrasal",
    title: "Phrasal Verbs (100+)",
    note: "Los más comunes con traducción y ejemplo.",
    headers: ["Phrasal", "Traducción", "Ejemplo"],
    rows: [
      ["bring up", "sacar (un tema) / criar", "She brought up an interesting point."],
      ["call off", "cancelar", "They called off the meeting due to the storm."],
      ["carry on", "continuar", "Carry on with your work, please."],
      ["come across", "encontrarse con", "I came across an old friend yesterday."],
      ["find out", "averiguar", "We need to find out the cause."],
      ["get along (with)", "llevarse bien", "Do you get along with your neighbors?"],
      ["get back", "volver", "I'll get back to you soon."],
      ["get over", "superar", "It took her a year to get over the loss."],
      ["give up", "rendirse / dejar (un hábito)", "He gave up smoking."],
      ["go on", "seguir", "Go on, I'm listening."],
      ["go out", "salir", "We went out for dinner."],
      ["look after", "cuidar de", "Can you look after the kids?"],
      ["look for", "buscar", "I'm looking for my keys."],
      ["look forward to", "esperar con ganas", "I look forward to hearing from you."],
      ["look into", "investigar", "The police are looking into the case."],
      ["make up", "inventar / reconciliarse", "They made up after the argument."],
      ["pick up", "recoger / aprender", "I picked up some French in Paris."],
      ["put off", "posponer", "Let's put off the meeting until Monday."],
      ["run out (of)", "quedarse sin", "We ran out of milk."],
      ["set up", "montar / configurar", "They set up a new company."],
      ["take off", "despegar / quitarse", "The plane took off on time."],
      ["take over", "hacerse cargo", "She took over as manager."],
      ["turn down", "rechazar / bajar (volumen)", "He turned down the offer."],
      ["turn up", "aparecer / subir (volumen)", "Turn up the music, please."],
      ["work out", "hacer ejercicio / resolver", "We worked out a solution."]
    ]
  },

  /* ==============================
     Idioms (100)
     ============================== */
  idioms: {
    id: "idioms",
    title: "Idioms (100+)",
    note: "Expresiones hechas con significado figurado y ejemplo.",
    headers: ["Expresión", "Significado", "Ejemplo"],
    rows: [
		["break the ice", "romper el hielo", "The joke helped break the ice at the meeting."],
		["hit the sack", "irse a dormir", "I'm tired; I'll hit the sack."],
		["piece of cake", "pan comido", "The exam was a piece of cake."],
		["once in a blue moon", "muy de vez en cuando", "He visits once in a blue moon."],
		["cost an arm and a leg", "costar un ojo de la cara", "That car costs an arm and a leg."],
		["spill the beans", "contar un secreto", "Who spilled the beans?"],
		["under the weather", "enfermo/a", "I'm feeling under the weather today."],
		["beat around the bush", "andarse por las ramas", "Stop beating around the bush!"],
		["hit the nail on the head", "dar en el clavo", "You hit the nail on the head."],
		["pull someone’s leg", "tomar el pelo", "Are you pulling my leg?"],
		["bark up the wrong tree", "equivocarse de objetivo", "You're barking up the wrong tree."],
		["a blessing in disguise", "no hay mal que por bien no venga", "Losing my job was a blessing in disguise."],
		["bite the bullet", "hacer de tripas corazón", "I had to bite the bullet and work with him."],
		["call it a day", "dar por terminado el día", "Let's call it a day and go home."],
		["cut corners", "hacer algo de mala manera para ahorrar", "They really cut corners when building this house."],
		["get out of hand", "írsele de las manos", "The party got out of hand."],
		["go back to the drawing board", "volver a empezar", "Our plan failed, so let's go back to the drawing board."],
		["hang in there", "aguantar, no rendirse", "I know it's tough, but hang in there."],
		["it's not rocket science", "no es tan difícil", "Come on, it's not rocket science."],
		["let the cat out of the bag", "revelar un secreto", "He let the cat out of the bag about the surprise party."],
		["make a long story short", "resumiendo", "To make a long story short, we won."],
		["miss the boat", "perder la oportunidad", "I missed the boat on that job offer."],
		["on the ball", "estar atento, ser competente", "She's always on the ball."],
		["so far so good", "hasta ahora todo bien", "How's the project going? So far so good."],
		["speak of the devil", "hablando del rey de Roma", "Speak of the devil, here comes Sarah now."],
		["that's the last straw", "esta es la gota que colma el vaso", "Losing my keys was the last straw."],
		["the best of both worlds", "lo mejor de dos mundos", "She works from home and has the best of both worlds."],
		["time flies", "el tiempo vuela", "Time flies when you're having fun."],
		["to get cold feet", "echarse para atrás por miedo", "He got cold feet before the wedding."],
		["a dime a dozen", "muy común, a patadas", "Experts in this field are a dime a dozen."],
		["add insult to injury", "echar más leña al fuego", "To add insult to injury, they charged me for the mistake."],
		["bite off more than you can chew", "quien mucho abarca, poco aprieta", "I think I bit off more than I can chew with this project."],
		["burn the midnight oil", "trabajar hasta muy tarde", "I have to burn the midnight oil to finish this report."],
		["can't judge a book by its cover", "las apariencias engañan", "He seems quiet, but you can't judge a book by its cover."],
		["catch-22", "un círculo vicioso, un callejón sin salida", "It's a catch-22 situation: you need experience to get a job, but you need a job to get experience."],
		["cross that bridge when you come to it", "ya se verá, no adelantar acontecimientos", "I'm worried about the presentation, but I'll cross that bridge when I come to it."],
		["cry over spilt milk", "lamentarse por algo que no tiene remedio", "There's no use crying over spilt milk."],
		["curiosity killed the cat", "la curiosidad mató al gato", "Don't ask so many questions. Curiosity killed the cat."],
		["cut to the chase", "ir al grano", "Let's cut to the chase. What's the problem?"],
		["don't count your chickens before they hatch", "no vendas la piel del oso antes de cazarlo", "I think I'll get the promotion, but I don't want to count my chickens before they hatch."],
		["don't give up your day job", "mejor dedícate a otra cosa", "Your singing is terrible. Don't give up your day job."],
		["don't put all your eggs in one basket", "no te juegues todo a una sola carta", "Diversify your investments. Don't put all your eggs in one basket."],
		["every cloud has a silver lining", "no hay mal que por bien no venga", "I was laid off, but every cloud has a silver lining, and now I can travel."],
		["feel a bit under the weather", "sentirse un poco enfermo", "I'm not coming to the party; I'm feeling a bit under the weather."],
		["get a taste of your own medicine", "probar tu propia medicina", "He's always rude to people, but he got a taste of his own medicine today."],
		["get your act together", "ponerse las pilas, organizarse", "You need to get your act together if you want to pass the exam."],
		["give someone the benefit of the doubt", "darle a alguien el beneficio de la duda", "I'll give him the benefit of the doubt and assume he didn't mean it."],
		["go down in flames", "fracasar estrepitosamente", "The project went down in flames."],
		["he has bigger fish to fry", "tener cosas más importantes que hacer", "He won't worry about that; he has bigger fish to fry."],
		["hit the books", "ponerse a estudiar", "I have to hit the books for my finals."],
		["ignorance is bliss", "la ignorancia es la felicidad", "I don't want to know the details. Ignorance is bliss."],
		["in a nutshell", "en pocas palabras", "In a nutshell, we need more funding."],
		["it takes two to tango", "se necesitan dos para bailar un tango (la culpa es de ambos)", "She blames him, but it takes two to tango."],
		["jump on the bandwagon", "subirse al carro", "Everyone is buying that new phone, so I decided to jump on the bandwagon."],
		["keep something at bay", "mantener algo a raya", "The vaccination helps to keep the virus at bay."],
		["kill two birds with one stone", "matar dos pájaros de un tiro", "I can kill two birds with one stone by listening to English podcasts while I exercise."],
		["let sleeping dogs lie", "es mejor no remover el pasado", "Don't mention the argument again. Let sleeping dogs lie."],
		["let someone off the hook", "perdonarle a alguien, dejarle escapar", "He made a mistake, but I'll let him off the hook this time."],
		["like a chicken with its head cut off", "como pollo sin cabeza", "He was running around like a chicken with its head cut off."],
		["look before you leap", "mira antes de saltar", "You should always look before you leap when making big decisions."],
		["method to my madness", "tener un método para la locura", "It seems chaotic, but there's a method to my madness."],
		["not my cup of tea", "no ser de mi gusto", "Horror movies are not my cup of tea."],
		["off the top of my head", "así de memoria, sin pensarlo mucho", "Off the top of my head, I think there are about 20 people coming."],
		["on the same page", "estar en la misma onda, de acuerdo", "Let's have a meeting to make sure we're all on the same page."],
		["out of the blue", "de la nada, inesperadamente", "He contacted me out of the blue after ten years."],
		["put a sock in it", "cállate la boca", "Put a sock in it! I'm trying to concentrate."],
		["rain on someone's parade", "aguarle la fiesta a alguien", "I don't want to rain on your parade, but the tickets are sold out."],
		["rock the boat", "crear problemas, agitar las aguas", "Don't rock the boat by complaining."],
		["see eye to eye", "estar de acuerdo", "We don't see eye to eye on politics."],
		["sit on the fence", "ser indeciso, no tomar partido", "You can't sit on the fence anymore; you have to choose."],
		["slow and steady wins the race", "lento pero seguro se gana la carrera", "Don't rush. Slow and steady wins the race."],
		["snowed under", "estar hasta arriba de trabajo", "I'm completely snowed under with work this week."],
		["steal someone's thunder", "robarle el protagonismo a alguien", "She stole my thunder by announcing her engagement right after I announced mine."],
		["straight from the horse's mouth", "de primera mano", "I heard it straight from the horse's mouth."],
		["take it with a grain of salt", "tomárselo con pinzas, no creérselo del todo", "Take his stories with a grain of salt; he tends to exaggerate."],
		["the ball is in your court", "la pelota está en tu tejado", "I've done my part. The ball is in your court now."],
		["the devil's advocate", "el abogado del diablo", "Let me play devil's advocate for a moment."],
		["the early bird gets the worm", "a quien madruga, Dios le ayuda", "I get up at 6 AM every day. The early bird gets the worm."],
		["the elephant in the room", "un problema obvio que nadie quiere mencionar", "We need to address the elephant in the room: our budget deficit."],
		["throw caution to the wind", "tirar la casa por la ventana, ser temerario", "She threw caution to the wind and quit her job to travel."],
		["turn a blind eye", "hacer la vista gorda", "The teacher turned a blind eye to the student cheating."],
		["up in the air", "en el aire, sin decidir", "Our travel plans are still up in the air."],
		["walking on eggshells", "andar con pies de plomo", "I'm always walking on eggshells around my boss."],
		["waste of time", "pérdida de tiempo", "Arguing with him is a waste of time."],
		["water under the bridge", "agua pasada", "We used to argue, but that's all water under the bridge now."],
		["wear your heart on your sleeve", "ser muy transparente con tus sentimientos", "He wears his heart on his sleeve."],
		["when it rains, it pours", "las desgracias nunca vienen solas", "First I lost my wallet, and then my car broke down. When it rains, it pours."],
		["you can't have your cake and eat it too", "no se puede tener todo en la vida", "He wants to work less but earn more. You can't have your cake and eat it too."],
		["you can't teach an old dog new tricks", "loro viejo no aprende a hablar", "My grandpa refuses to use a computer. You can't teach an old dog new tricks."],
		["a snowball effect", "efecto bola de nieve", "The small protest started a snowball effect across the country."],
		["an arm and a leg", "un ojo de la cara", "This new phone costs an arm and a leg."],
		["at the drop of a hat", "en un santiamén", "She's ready to travel at the drop of a hat."],
		["back to square one", "volver al punto de partida", "The experiment failed, so we're back to square one."],
		["birds of a feather flock together", "Dios los cría y ellos se juntan", "They are all interested in the same music. Birds of a feather flock together."],
		["break a leg", "mucha mierda (buena suerte)", "Break a leg in your performance tonight!"]
    ]
  },

  /* ==============================
     Conectores (50+)
     ============================== */
  connectors: {
    id: "connectors",
    title: "Conectores",
    note: "Palabras para unir ideas. Conoce su traducción y uso con ejemplos.",
    headers: ["Conector", "Traducción", "Uso", "Ejemplo"],
    rows: [
		{ type: "heading", text: "Contraste" },
		["however", "sin embargo", "Introducir una idea que contrasta", "He is rich; however, he is not happy."],
		["nevertheless", "no obstante", "Similar a 'however', más formal", "The task was difficult; nevertheless, they succeeded."],
		["although / though", "aunque", "Mostrar una concesión o contraste", "Although it was raining, we went for a walk."],
		["even though", "aunque / a pesar de que", "Enfatiza el contraste más que 'although'", "Even though he studied, he failed the exam."],
		["whereas", "mientras que", "Comparar dos ideas o hechos opuestos", "She is very outgoing, whereas her brother is shy."],
		["while", "mientras que / aunque", "Contraste o para hablar de dos acciones simultáneas", "While I like pop music, my sister prefers rock."],
		["on the other hand", "por otro lado", "Presentar un punto de vista diferente", "The city is vibrant; on the other hand, it's very expensive."],
		["in contrast", "en contraste", "Señalar una diferencia clara", "In contrast to her sister, she is very tall."],
		["despite / in spite of", "a pesar de", "Introducir un obstáculo", "Despite the rain, they played the match."],
		{ type: "heading", text: "Adición" },
		["and", "y", "Añadir un elemento similar", "I like coffee and tea."],
		["also", "también", "Añadir una idea o hecho nuevo", "She speaks French and also speaks German."],
		["moreover", "además", "Añadir un argumento de más peso (formal)", "The report is badly written. Moreover, it's inaccurate."],
		["furthermore", "además / es más", "Similar a 'moreover', añade énfasis (formal)", "He is lazy. Furthermore, he is dishonest."],
		["in addition", "además", "Añadir información extra", "In addition to his salary, he receives bonuses."],
		["besides", "además", "Añadir otra razón", "I don't want to go; besides, I'm tired."],
		["as well", "también", "Se suele colocar al final de la frase", "He speaks Spanish and English as well."],
		["not only... but also", "no solo... sino también", "Enfatizar dos elementos conectados", "She is not only smart but also very kind."],
		{ type: "heading", text: "Causa" },
		["because", "porque", "Indicar la razón de algo", "He stayed at home because he was sick."],
		["since", "ya que / puesto que", "Indicar una causa ya conocida", "Since you are here, you can help me."],
		["as", "como / puesto que", "Similar a 'since', a menudo al principio", "As it was getting late, we decided to go home."],
		["due to", "debido a", "Indicar la causa (seguido de sustantivo)", "The flight was canceled due to the storm."],
		["owing to", "debido a", "Similar a 'due to' (formal)", "Owing to a lack of funds, the project was stopped."],
		{ type: "heading", text: "Consecuencia" },
		["so", "así que / por lo tanto", "Indicar un resultado o consecuencia", "It was cold, so I put on a coat."],
		["therefore", "por lo tanto", "Indicar una consecuencia lógica (formal)", "He didn't study; therefore, he failed."],
		["thus", "así / por consiguiente", "Indicar un resultado (muy formal)", "He trained hard and thus won the race."],
		["consequently", "por consiguiente", "Indicar el resultado de una acción", "She forgot to set her alarm and, consequently, was late."],
		["as a result", "como resultado", "Mostrar el resultado directo", "He ate too much. As a result, he felt sick."],
		["hence", "de ahí / por eso", "Indicar una conclusión (formal)", "The company is losing money, hence the need for cuts."],
		{ type: "heading", text: "Finalidad" },
		["to", "para", "Indicar el propósito (seguido de infinitivo)", "I went to the store to buy milk."],
		["in order to", "para", "Más formal que 'to' (seguido de infinitivo)", "He works hard in order to support his family."],
		["so as to", "para", "Similar a 'in order to' (formal)", "They left early so as to avoid traffic."],
		["so that", "para que", "Indicar propósito (seguido de una cláusula)", "I'll give you a map so that you can find the way."],
		{ type: "heading", text: "Orden y Secuencia" },
		["first(ly) / to begin with", "primero / para empezar", "Iniciar una lista de puntos", "Firstly, I want to thank you all for coming."],
		["second(ly)", "en segundo lugar", "Continuar la lista", "Secondly, let's discuss the budget."],
		["then / next", "luego / después", "Indicar el siguiente paso", "First, mix the flour and sugar. Then, add the eggs."],
		["after that", "después de eso", "Continuar la secuencia", "We had dinner, and after that, we watched a movie."],
		["finally / in the end", "finalmente / al final", "Indicar el último punto o el resultado", "Finally, I'd like to open the floor for questions."]
    ]
  },

  /* ==============================
     Adverbios
     ============================== */
  adverbs: {
    id: "adverbs",
    title: "Adverbios",
    note: "Palabras que modifican verbos, adjetivos u otros adverbios. Conoce su traducción y uso.",
    headers: ["Adverbio", "Traducción", "Categoría", "Ejemplo"],
    rows: [
		{ type: "heading", text: "Tiempo" },
		["now", "ahora", "Tiempo", "I am busy now."],
		["today", "hoy", "Tiempo", "She is leaving today."],
		["yesterday", "ayer", "Tiempo", "I saw him yesterday."],
		["tomorrow", "mañana", "Tiempo", "The meeting is tomorrow."],
		["already", "ya", "Tiempo", "He has already finished."],
		["yet", "aún / ya", "Tiempo", "Have you eaten yet?"],
		["soon", "pronto", "Tiempo", "See you soon!"],
		["lately / recently", "últimamente / recientemente", "Tiempo", "I haven't seen her lately."],
		["then", "entonces / luego", "Tiempo", "First I'll work, then I'll rest."],
		["eventually", "finalmente / al final", "Tiempo", "He eventually found his keys."],
		{ type: "heading", text: "Frecuencia" },
		["always", "siempre", "Frecuencia", "She always arrives on time."],
		["usually", "normalmente / usualmente", "Frecuencia", "I usually walk to work."],
		["often", "a menudo", "Frecuencia", "We often go to the cinema."],
		["sometimes", "a veces", "Frecuencia", "Sometimes I feel tired."],
		["rarely / seldom", "rara vez", "Frecuencia", "He rarely complains."],
		["hardly ever", "casi nunca", "Frecuencia", "She hardly ever watches TV."],
		["never", "nunca", "Frecuencia", "I have never been to Japan."],
		{ type: "heading", text: "Modo" },
		["well", "bien", "Modo", "He plays the guitar very well."],
		["badly", "mal", "Modo", "The team played badly."],
		["carefully", "cuidadosamente", "Modo", "Please drive carefully."],
		["quickly", "rápidamente", "Modo", "She finished the test quickly."],
		["slowly", "lentamente", "Modo", "He was walking slowly."],
		["quietly", "silenciosamente", "Modo", "The cat moved quietly."],
		["loudly", "ruidosamente", "Modo", "He speaks too loudly."],
		["easily", "fácilmente", "Modo", "She can easily solve the problem."],
		["clearly", "claramente", "Modo", "Please speak more clearly."],
		{ type: "heading", text: "Lugar" },
		["here", "aquí", "Lugar", "Come here, please."],
		["there", "allí / ahí", "Lugar", "Your book is over there."],
		["everywhere", "en todas partes", "Lugar", "I've looked everywhere for my keys."],
		["nowhere", "en ninguna parte", "Lugar", "This road leads nowhere."],
		["abroad", "en el extranjero", "Lugar", "He has lived abroad for ten years."],
		["indoors / outdoors", "adentro / afuera", "Lugar", "It's raining, let's stay indoors."],
		["upstairs / downstairs", "arriba / abajo (en un edificio)", "Lugar", "The bedrooms are upstairs."],
		{ type: "heading", text: "Grado" },
		["very", "muy", "Grado", "It is very cold today."],
		["quite", "bastante", "Grado", "The movie was quite good."],
		["rather", "bastante / más bien", "Grado", "It's rather a difficult question."],
		["too", "demasiado", "Grado", "This coffee is too hot."],
		["enough", "suficiente", "Grado", "Is the water warm enough?"],
		["almost / nearly", "casi", "Grado", "I'm almost finished."],
		["completely", "completamente", "Grado", "I completely forgot about it."],
		["absolutely", "absolutamente", "Grado", "You are absolutely right."]
    ]
  },

  /* ==============================
     Preposiciones
     ============================== */
  prepositions: {
    id: "prepositions",
    title: "Preposiciones",
    note: "Palabras que conectan sustantivos con otras partes de la oración, indicando tiempo, lugar o dirección.",
    headers: ["Preposición", "Uso principal (Cuándo usarlo)", "Ejemplo (en contexto)"],
    rows: [
      ["about", "Sobre un tema, alrededor de", "We were talking about the movie. / He walked about the town."],
      ["above", "Por encima de, sin tocar", "The plane flew above the clouds."],
      ["across", "De un lado a otro (superficie)", "She swam across the river."],
      ["after", "Después de", "I will call you after lunch."],
      ["among", "Entre (tres o más elementos)", "He was among the crowd."],
      ["at", "Tiempos específicos (at 5 PM), lugares concretos (at the station)", "She arrived at 3 o'clock. We are at the airport."],
      ["before", "Antes de", "Please, finish your homework before dinner."],
      ["behind", "Detrás de", "The cat is hiding behind the sofa."],
      ["below", "Por debajo de, sin tocar", "The temperature is below zero."],
      ["beneath", "Debajo de (más formal que under)", "The treasure was buried beneath the tree."],
      ["beside", "Al lado de", "He sat beside her."],
      ["between", "Entre (dos elementos)", "The shop is between the bank and the library."],
      ["by", "Agente en pasiva, plazo límite, medio de transporte", "The book was written by him. / Finish it by Friday."],
      ["down", "Hacia abajo", "He walked down the hill."],
      ["for", "Duración, propósito, destinatario", "We walked for three hours. / This gift is for her."],
      ["from", "Origen en tiempo o espacio", "He is from Spain. / The store is open from 9 to 5."],
      ["in", "Periodos largos (in April), lugares grandes (in London), espacios cerrados (in the box)", "My birthday is in June. He lives in a big city."],
      ["into", "Movimiento hacia adentro", "He jumped into the water."],
      ["like", "Como, parecido a", "She sings like an angel."],
      ["near", "Cerca de", "My house is near the park."],
      ["of", "De (posesión, pertenencia)", "He is a friend of mine."],
      ["off", "Indica separación, quitar", "Please turn off the light. / The button came off."],
      ["on", "Días y fechas (on Monday), superficies (on the table), transporte público (on the bus)", "The book is on the desk. I'll see you on Friday."],
      ["over", "Posición superior, más de una cantidad", "The plane flew over the mountains. / You must be over 18."],
      ["since", "Desde un punto en el tiempo", "I have lived here since 2010."],
      ["through", "A través de (movimiento de un lado a otro de algo)", "They walked through the forest."],
      ["throughout", "A lo largo de, en todo", "The news spread throughout the country."],
      ["till / until", "Hasta (un momento en el tiempo)", "Wait until I get back."],
      ["to", "Dirección, destino, receptor", "We are going to the cinema. / She gave the keys to him."],
      ["under", "Posición inferior (debajo de)", "The cat is under the bed."],
      ["up", "Hacia arriba", "She looked up at the sky."],
      ["upon", "Sobre (más formal que 'on')", "Once upon a time..."],
      ["with", "Compañía, instrumento", "I'm going with my family. / Write it with a pencil."],
      ["without", "Sin", "I can't live without music."]
    ]
  },

  /* ==============================
     Falsos Amigos
     ============================== */
  false_friends: {
    id: "false_friends",
    title: "Falsos Amigos (100+)",
    note: "Palabras en inglés que se parecen al español pero tienen significados muy diferentes.",
    headers: ["Palabra (Inglés)", "Significado Real", "Falso Amigo (Español)"],
    rows: [
      ["actual", "real, verdadero", "actual (current)"],
      ["actually", "en realidad, de hecho", "actualmente (currently)"],
      ["advertisement", "anuncio publicitario", "advertencia (warning)"],
      ["advice", "consejo", "aviso (notice, warning)"],
      ["to advise", "aconsejar", "avisar (to warn, to notify)"],
      ["agenda", "orden del día", "agenda (diary, planner)"],
      ["air", "aire", "aire (look, appearance)"],
      ["anthem", "himno", "antena (antenna)"],
      ["application", "solicitud (de trabajo)", "aplicación (diligence)"],
      ["argument", "discusión, pelea", "argumento (plot, reasoning)"],
      ["assist", "ayudar, atender", "asistir (to attend)"],
      ["avocado", "aguacate", "abogado (lawyer)"],
      ["bachelor", "soltero, licenciado", "bachiller (high school graduate)"],
      ["balloon", "globo", "balón (ball)"],
      ["bizarre", "extraño, estrafalario", "bizarro (brave, gallant)"],
      ["bland", "soso, insípido", "blando (soft)"],
      ["bomb", "bomba (explosivo)", "bomba (pump)"],
      ["brave", "valiente", "bravo (angry, fierce)"],
      ["buffet", "bufé, autoservicio", "bufete (law firm)"],
      ["cafeteria", "comedor (de colegio, empresa)", "cafetería (coffee shop)"],
      ["camera", "cámara (fotográfica)", "cámara (chamber, room)"],
      ["campus", "campus universitario", "campo (field, countryside)"],
      ["carpet", "alfombra, moqueta", "carpeta (folder)"],
      ["casualty", "víctima, baja (en guerra)", "casualidad (coincidence, chance)"],
      ["choke", "asfixiarse, atragantarse", "chocar (to crash, to collide)"],
      ["college", "universidad, escuela superior", "colegio (school, high school)"],
      ["commodity", "materia prima, producto", "comodidad (comfort)"],
      ["complexion", "tez, cutis", "complexión (constitution, build)"],
      ["compromise", "acuerdo, concesión", "compromiso (commitment, obligation)"],
      ["conductor", "director de orquesta, cobrador", "conductor (driver)"],
      ["constipated", "estreñido", "constipado (to have a cold)"],
      ["content", "contenido", "contento (happy)"],
      ["contest", "concurso", "contestar (to answer)"],
      ["convenient", "práctico, cómodo", "conveniente (advisable, appropriate)"],
      ["corpse", "cadáver", "corzo (roe deer)"],
      ["curse", "maldición", "curso (course)"],
      ["deception", "engaño, fraude", "decepción (disappointment)"],
      ["delicate", "delicado, frágil", "delito (crime)"],
      ["demand", "exigir, demanda (eco.)", "demandar (to sue)"],
      ["dessert", "postre", "desierto (desert)"],
      ["disgrace", "vergüenza, deshonra", "desgracia (misfortune, tragedy)"],
      ["disgust", "asco, repugnancia", "disgusto (annoyance, displeasure)"],
      ["diversion", "desvío, distracción", "diversión (fun)"],
      ["embarrassed", "avergonzado", "embarazada (pregnant)"],
      ["emotive", "emotivo (que causa emoción)", "emotivo (emotional, sensitive)"],
      ["eventually", "finalmente, al final", "eventualmente (possibly, by chance)"],
      ["exit", "salida", "éxito (success)"],
      ["fabric", "tela, tejido", "fábrica (factory)"],
      ["facility", "instalación, servicio", "facilidad (ease)"],
      ["figure", "cifra, figura, silueta", "figura (shape, celebrity)"],
      ["firm", "empresa, firme", "firma (signature)"],
      ["focus", "enfocar, centro de atención", "foco (light bulb, focus)"],
      ["form", "formulario", "forma (shape, way)"],
      ["gracious", "amable, cortés", "gracioso (funny)"],
      ["grade", "nota, curso", "grado (degree)"],
      ["grocery store", "tienda de comestibles", "grosería (rudeness)"],
      ["harass", "acosar", "arrasar (to destroy)"],
      ["huge", "enorme", "huyo (I flee)"],
      ["idiom", "expresión idiomática", "idioma (language)"],
      ["ignore", "no hacer caso, ignorar", "ignorar (not to know)"],
      ["introduce", "presentar a alguien", "introducir (to insert, to put in)"],
      ["involved", "involucrado, implicado", "envuelto (wrapped)"],
      ["jam", "mermelada, atasco", "jamón (ham)"],
      ["large", "grande", "largo (long)"],
      ["lecture", "conferencia, clase magistral", "lectura (reading)"],
      ["library", "biblioteca", "librería (bookshop)"],
      ["luxury", "lujo", "lujuria (lust)"],
      ["major", "principal, especialidad (carrera)", "mayor (older, bigger)"],
      ["media", "medios de comunicación", "media (sock, average)"],
      ["misery", "tristeza profunda, miseria", "miseria (poverty)"],
      ["molest", "abusar sexualmente", "molestar (to bother, to annoy)"],
      ["notice", "darse cuenta, aviso", "noticia (news)"],
      ["nude", "desnudo", "nudo (knot)"],
      ["once", "una vez", "once (eleven)"],
      ["panic", "pánico", "pánico (stage fright)"],
      ["parents", "padres (padre y madre)", "parientes (relatives)"],
      ["particular", "concreto, específico", "particular (private)"],
      ["pass", "aprobar (examen)", "pasar (to pass, to happen)"],
      ["petrol", "gasolina", "petróleo (oil)"],
      ["policy", "política (de empresa), póliza", "policía (police)"],
      ["preservative", "conservante", "preservativo (condom)"],
      ["pretend", "fingir", "pretender (to intend, to try)"],
      ["prospect", "perspectiva, posibilidad", "prospecto (leaflet, brochure)"],
      ["quiet", "tranquilo, silencioso", "quieto (still)"],
      ["realize", "darse cuenta", "realizar (to carry out, to make)"],
      ["record", "grabar, historial, disco", "recordar (to remember)"],
      ["remove", "quitar, eliminar", "remover (to stir)"],
      ["rest", "descansar, resto", "restar (to subtract)"],
      ["resume", "reanudar, currículum", "resumir (to summarize)"],
      ["rope", "cuerda, soga", "ropa (clothes)"],
      ["salad", "ensalada", "salado (salty)"],
      ["sane", "cuerdo, sensato", "sano (healthy)"],
      ["sensible", "sensato, razonable", "sensible (sensitive)"],
      ["signature", "firma", "asignatura (subject)"],
      ["soap", "jabón", "sopa (soup)"],
      ["suburb", "barrio residencial, afueras", "suburbio (slum, ghetto)"],
      ["success", "éxito", "suceso (event)"],
      ["support", "apoyar, sostener", "soportar (to put up with, to bear)"],
      ["sympathy", "compasión, pésame", "simpatía (friendliness, charm)"],
      ["terrific", "genial, fantástico", "terrorífico (terrifying)"],
      ["topic", "tema, asunto", "tópico (cliché)"],
      ["transport", "transportar", "transportar (to move emotionally)"],
      ["ultimate", "definitivo, final", "último (last)"],
      ["vicious", "cruel, malicioso", "vicioso (addicted)"]
    ]
  },

  /* ==============================
     Tiempos Verbales (resumen)
     ============================== */
  tenses: {
    id: "tenses",
    title: "Tiempos Verbales (Resumen)",
    note: "Forma + uso + ejemplo para los tiempos más usados.",
    headers: ["Tiempo", "Forma", "Uso", "Ejemplo"],
    rows: [
      ["Present Simple", "S + V (3ª sg: -s)", "Hábitos, verdades generales", "She works every day."],
      ["Present Continuous", "S + am/is/are + V-ing", "Acción en progreso, planes cercanos", "They are studying now."],
      ["Present Perfect", "S + have/has + Vpp", "Experiencia, resultado presente", "I have visited London."],
      ["Past Simple", "S + V-ed / IRR (past)", "Acción terminada en el pasado (tiempo definido)", "We watched a film yesterday."],
      ["Past Continuous", "S + was/were + V-ing", "Acción en progreso en el pasado", "I was cooking when you called."],
      ["Past Perfect", "S + had + Vpp", "Acción anterior a otra pasada", "She had left before I arrived."],
      ["Future Will", "S + will + V", "Predicciones, decisiones espontáneas", "I'll help you."],
      ["Be Going To", "S + am/is/are + going to + V", "Planes/Intenciones; evidencia presente", "It's going to rain."],
      ["Present Perfect Continuous", "S + have/has been + V-ing", "Duración hasta el presente", "He has been working for 3 hours."]
    ]
  },

  /* ==============================
     Comparativos y Superlativos
     ============================== */
  comparatives: {
    id: "comparatives",
    title: "Comparativos y Superlativos",
    note: "Reglas, terminaciones e irregulares.",
    headers: ["Tipo", "Regla / Lista", "Ejemplo"],
    rows: [
      ["Corto (1 sílaba)", "adj + -er / the + adj + -est", "tall → taller → the tallest"],
      ["Termina en -y", "y → i + -er / -est", "happy → happier → the happiest"],
      ["Largo (≥2 sílabas)", "more / most", "interesting → more interesting → the most interesting"],
      ["Doblar consonante", "CVC → doble consonante + -er/-est", "big → bigger → the biggest"],
      ["Irregulares", "good → better → the best; bad → worse → the worst; far → farther/further → the farthest/furthest", "—"]
    ]
  },

  /* ==============================
     Extras
     ============================== */
  extras: {
    id: "extras",
    title: "Extras",
    note: "Números, fechas y abreviaturas útiles.",
    headers: ["Tema", "Lista / Nota"],
    rows: [
      ["Números", "1–10: one, two, three...; decenas: twenty, thirty...; centenas: one hundred..."],
      ["Fechas", "on + día (on Monday); in + mes/año (in July, in 2025); at + hora (at 7 pm)"],
      ["Abreviaturas Comunes", "ASAP (As Soon As Possible), FYI (For Your Information), ETA (Estimated Time of Arrival), DIY (Do It Yourself), TBD (To Be Determined)"]
    ]
  }
};

// Exponer globalmente
window.DATA = DATA;